//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.02.28 at 03:32:10 PM GMT+04:00 
//


package ru.tfoms.schemas.person;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MilSvcPerson complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MilSvcPerson"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="oip" type="{http://ffoms.ru/types/commonTypes}Oip" minOccurs="0"/&gt;
 *         &lt;element name="localPersonIndex" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="personInfo" type="{http://ffoms.ru/types/insuranceSuspendSchema}PersonFioDr"/&gt;
 *         &lt;element name="dudl" type="{http://ffoms.ru/types/commonTypes}PersonDocIdentSerNum"/&gt;
 *         &lt;element name="snils" type="{http://ffoms.ru/types/commonTypes}SnilsType" minOccurs="0"/&gt;
 *         &lt;element name="milSvc" type="{http://ffoms.ru/types/insuranceSuspendSchema}MilSvcData"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MilSvcPerson", namespace = "http://ffoms.ru/types/insuranceSuspendSchema", propOrder = {
    "oip",
    "localPersonIndex",
    "personInfo",
    "dudl",
    "snils",
    "milSvc"
})
public class MilSvcPerson {

    protected String oip;
    @XmlElement(required = true)
    protected String localPersonIndex;
    @XmlElement(required = true)
    protected PersonFioDr personInfo;
    @XmlElement(required = true)
    protected PersonDocIdentSerNum dudl;
    protected String snils;
    @XmlElement(required = true)
    protected MilSvcData milSvc;

    /**
     * Gets the value of the oip property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOip() {
        return oip;
    }

    /**
     * Sets the value of the oip property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOip(String value) {
        this.oip = value;
    }

    /**
     * Gets the value of the localPersonIndex property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocalPersonIndex() {
        return localPersonIndex;
    }

    /**
     * Sets the value of the localPersonIndex property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocalPersonIndex(String value) {
        this.localPersonIndex = value;
    }

    /**
     * Gets the value of the personInfo property.
     * 
     * @return
     *     possible object is
     *     {@link PersonFioDr }
     *     
     */
    public PersonFioDr getPersonInfo() {
        return personInfo;
    }

    /**
     * Sets the value of the personInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link PersonFioDr }
     *     
     */
    public void setPersonInfo(PersonFioDr value) {
        this.personInfo = value;
    }

    /**
     * Gets the value of the dudl property.
     * 
     * @return
     *     possible object is
     *     {@link PersonDocIdentSerNum }
     *     
     */
    public PersonDocIdentSerNum getDudl() {
        return dudl;
    }

    /**
     * Sets the value of the dudl property.
     * 
     * @param value
     *     allowed object is
     *     {@link PersonDocIdentSerNum }
     *     
     */
    public void setDudl(PersonDocIdentSerNum value) {
        this.dudl = value;
    }

    /**
     * Gets the value of the snils property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSnils() {
        return snils;
    }

    /**
     * Sets the value of the snils property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSnils(String value) {
        this.snils = value;
    }

    /**
     * Gets the value of the milSvc property.
     * 
     * @return
     *     possible object is
     *     {@link MilSvcData }
     *     
     */
    public MilSvcData getMilSvc() {
        return milSvc;
    }

    /**
     * Sets the value of the milSvc property.
     * 
     * @param value
     *     allowed object is
     *     {@link MilSvcData }
     *     
     */
    public void setMilSvc(MilSvcData value) {
        this.milSvc = value;
    }

}
