//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.03.09 at 11:47:09 AM GMT+04:00 
//


package ru.tfoms.schemas.person;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ru.tfoms.schemas.person package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ru.tfoms.schemas.person
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SuspendOmsPolicyStartRequest }
     * 
     */
    public SuspendOmsPolicyStartRequest createSuspendOmsPolicyStartRequest() {
        return new SuspendOmsPolicyStartRequest();
    }

    /**
     * Create an instance of {@link CommonRequestType }
     * 
     */
    public CommonRequestType createCommonRequestType() {
        return new CommonRequestType();
    }

    /**
     * Create an instance of {@link ListOfMilSvcPerson }
     * 
     */
    public ListOfMilSvcPerson createListOfMilSvcPerson() {
        return new ListOfMilSvcPerson();
    }

    /**
     * Create an instance of {@link SuspendOmsPolicyStartResponse }
     * 
     */
    public SuspendOmsPolicyStartResponse createSuspendOmsPolicyStartResponse() {
        return new SuspendOmsPolicyStartResponse();
    }

    /**
     * Create an instance of {@link AsyncStartResponse }
     * 
     */
    public AsyncStartResponse createAsyncStartResponse() {
        return new AsyncStartResponse();
    }

    /**
     * Create an instance of {@link CommonResponseType }
     * 
     */
    public CommonResponseType createCommonResponseType() {
        return new CommonResponseType();
    }

    /**
     * Create an instance of {@link ListOfErrors }
     * 
     */
    public ListOfErrors createListOfErrors() {
        return new ListOfErrors();
    }

    /**
     * Create an instance of {@link SuspendOmsPolicyPollRequest }
     * 
     */
    public SuspendOmsPolicyPollRequest createSuspendOmsPolicyPollRequest() {
        return new SuspendOmsPolicyPollRequest();
    }

    /**
     * Create an instance of {@link AsyncPollRequest }
     * 
     */
    public AsyncPollRequest createAsyncPollRequest() {
        return new AsyncPollRequest();
    }

    /**
     * Create an instance of {@link SuspendOmsPolicyPollResponse }
     * 
     */
    public SuspendOmsPolicyPollResponse createSuspendOmsPolicyPollResponse() {
        return new SuspendOmsPolicyPollResponse();
    }

    /**
     * Create an instance of {@link AsyncPollResponse }
     * 
     */
    public AsyncPollResponse createAsyncPollResponse() {
        return new AsyncPollResponse();
    }

    /**
     * Create an instance of {@link MilPersonResult }
     * 
     */
    public MilPersonResult createMilPersonResult() {
        return new MilPersonResult();
    }

    /**
     * Create an instance of {@link MilSvcPerson }
     * 
     */
    public MilSvcPerson createMilSvcPerson() {
        return new MilSvcPerson();
    }

    /**
     * Create an instance of {@link PersonFioDr }
     * 
     */
    public PersonFioDr createPersonFioDr() {
        return new PersonFioDr();
    }

    /**
     * Create an instance of {@link MilSvcData }
     * 
     */
    public MilSvcData createMilSvcData() {
        return new MilSvcData();
    }

    /**
     * Create an instance of {@link Attach }
     * 
     */
    public Attach createAttach() {
        return new Attach();
    }

    /**
     * Create an instance of {@link ResponseErrorData }
     * 
     */
    public ResponseErrorData createResponseErrorData() {
        return new ResponseErrorData();
    }

    /**
     * Create an instance of {@link Contact }
     * 
     */
    public Contact createContact() {
        return new Contact();
    }

    /**
     * Create an instance of {@link PersonDocIdentShortBase }
     * 
     */
    public PersonDocIdentShortBase createPersonDocIdentShortBase() {
        return new PersonDocIdentShortBase();
    }

    /**
     * Create an instance of {@link PersonDocIdentFullBase }
     * 
     */
    public PersonDocIdentFullBase createPersonDocIdentFullBase() {
        return new PersonDocIdentFullBase();
    }

    /**
     * Create an instance of {@link PersonDocIdentSerNum }
     * 
     */
    public PersonDocIdentSerNum createPersonDocIdentSerNum() {
        return new PersonDocIdentSerNum();
    }

    /**
     * Create an instance of {@link Address }
     * 
     */
    public Address createAddress() {
        return new Address();
    }

    /**
     * Create an instance of {@link OmsPolicy }
     * 
     */
    public OmsPolicy createOmsPolicy() {
        return new OmsPolicy();
    }

    /**
     * Create an instance of {@link PcyData }
     * 
     */
    public PcyData createPcyData() {
        return new PcyData();
    }

    /**
     * Create an instance of {@link PaginationRequestType }
     * 
     */
    public PaginationRequestType createPaginationRequestType() {
        return new PaginationRequestType();
    }

    /**
     * Create an instance of {@link PaginationResponseType }
     * 
     */
    public PaginationResponseType createPaginationResponseType() {
        return new PaginationResponseType();
    }

}
