//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.02.28 at 03:32:10 PM GMT+04:00 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://ffoms.ru/types/commonTypes", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package ru.tfoms.schemas.person;
