//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.02.28 at 09:14:02 AM GMT+04:00 
//


package ru.tfoms.schemas.person;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://ffoms.ru/types/commonTypes}CommonRequestType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="persons" type="{http://ffoms.ru/types/insuranceSuspendSchema}ListOfMilSvcPerson"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "persons"
})
@XmlRootElement(name = "suspendOmsPolicyStartRequest", namespace = "http://ffoms.ru/types/insuranceSuspendSchema")
public class SuspendOmsPolicyStartRequest
    extends CommonRequestType
{

    @XmlElement(namespace = "http://ffoms.ru/types/insuranceSuspendSchema", required = true)
    protected ListOfMilSvcPerson persons;

    /**
     * Gets the value of the persons property.
     * 
     * @return
     *     possible object is
     *     {@link ListOfMilSvcPerson }
     *     
     */
    public ListOfMilSvcPerson getPersons() {
        return persons;
    }

    /**
     * Sets the value of the persons property.
     * 
     * @param value
     *     allowed object is
     *     {@link ListOfMilSvcPerson }
     *     
     */
    public void setPersons(ListOfMilSvcPerson value) {
        this.persons = value;
    }

}
