//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.03.01 at 01:57:17 PM GMT+04:00 
//


package ru.tfoms.schemas.person;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://ffoms.ru/types/commonTypes}AsyncPollResponse"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="milPersonResult" type="{http://ffoms.ru/types/insuranceSuspendSchema}MilPersonResult" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "milPersonResult"
})
@XmlRootElement(name = "suspendOmsPolicyPollResponse", namespace = "http://ffoms.ru/types/insuranceSuspendSchema")
public class SuspendOmsPolicyPollResponse
    extends AsyncPollResponse
{

    @XmlElement(namespace = "http://ffoms.ru/types/insuranceSuspendSchema")
    protected List<MilPersonResult> milPersonResult;

    /**
     * Gets the value of the milPersonResult property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the milPersonResult property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMilPersonResult().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MilPersonResult }
     * 
     * 
     */
    public List<MilPersonResult> getMilPersonResult() {
        if (milPersonResult == null) {
            milPersonResult = new ArrayList<MilPersonResult>();
        }
        return this.milPersonResult;
    }

}
